### ISSUE TITLE
cannot run the code

### ISSUE THREAD

**Issue by Stephanessy** [junfu1115/DANet#113]
env: python 3.6, cuda 9.0, pytorch 0.4.1
try to run danet/train.py
error:
```
Traceback (most recent call last):
  File "/home/mmvc/anaconda3/envs/Rx/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 960, in _build_extension_module
    check=True)
  File "/home/mmvc/anaconda3/envs/SY_DANet/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 18, in <module>
    import encoding.utils as utils
  File "/home/mmvc/anaconda3/envs/SY_DANet/lib/python3.6/site-packages/encoding/__init__.py", line 13, in <module>
    from . import nn, functions, dilated, parallel, utils, models, datasets
  File "/home/mmvc/anaconda3/envs/SY_DANet/lib/python3.6/site-packages/encoding/nn/__init__.py", line 12, in <module>
    from .encoding import *
  File "/home/mmvc/anaconda3/envs/SY_DANet/lib/python3.6/site-packages/encoding/nn/encoding.py", line 19, in <module>
    from ..functions import scaledL2, aggregate, pairwise_cosine
  File "/home/mmvc/anaconda3/envs/SY_DANet/lib/python3.6/site-packages/encoding/functions/__init__.py", line 2, in <module>
    from .encoding import *
  File "/home/mmvc/anaconda3/envs/SY_DANet/lib/python3.6/site-packages/encoding/functions/encoding.py", line 14, in <module>
    from .. import lib
  File "/home/mmvc/anaconda3/envs/SY_DANet/lib/python3.6/site-packages/encoding/lib/__init__.py", line 12, in <module>
    ], build_directory=cpu_path, verbose=False)
  File "/home/mmvc/anaconda3/envs/Rx/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 658, in load
    is_python_module)
  File "/home/mmvc/anaconda3/envs/Rx/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 827, in _jit_compile
    with_cuda=with_cuda)
  File "/home/mmvc/anaconda3/envs/Rx/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 880, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/home/mmvc/anaconda3/envs/Rx/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 973, in _build_extension_module
    raise RuntimeError(message)
RuntimeError: Error building extension 'enclib_cpu': [1/2] c++ -MMD -MF roi_align_cpu.o.d -DTORCH_EXTENSION_NAME=enclib_cpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/mmvc/anaconda3/envs/Rx/lib/python3.6/site-packages/torch/include -isystem /home/mmvc/anaconda3/envs/Rx/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/mmvc/anaconda3/envs/Rx/lib/python3.6/site-packages/torch/include/TH -isystem /home/mmvc/anaconda3/envs/Rx/lib/python3.6/site-packages/torch/include/THC -isystem /home/mmvc/anaconda3/envs/SY_DANet/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++11 -c /home/mmvc/anaconda3/envs/SY_DANet/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp -o roi_align_cpu.o
FAILED: roi_align_cpu.o 
c++ -MMD -MF roi_align_cpu.o.d -DTORCH_EXTENSION_NAME=enclib_cpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/mmvc/anaconda3/envs/Rx/lib/python3.6/site-packages/torch/include -isystem /home/mmvc/anaconda3/envs/Rx/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/mmvc/anaconda3/envs/Rx/lib/python3.6/site-packages/torch/include/TH -isystem /home/mmvc/anaconda3/envs/Rx/lib/python3.6/site-packages/torch/include/THC -isystem /home/mmvc/anaconda3/envs/SY_DANet/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++11 -c /home/mmvc/anaconda3/envs/SY_DANet/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp -o roi_align_cpu.o
/home/mmvc/anaconda3/envs/SY_DANet/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp: In function ‘at::Tensor ROIAlignForwardCPU(const at::Tensor&, const at::Tensor&, int64_t, int64_t, double, int64_t)’:
/home/mmvc/anaconda3/envs/SY_DANet/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:407:30: error: ‘class at::DeprecatedTypeProperties’ has no member named ‘tensor’
   auto output = input.type().tensor({num_rois, channels, pooled_height, pooled_width});
                              ^
In file included from /home/mmvc/anaconda3/envs/Rx/lib/python3.6/site-packages/torch/include/ATen/ATen.h:9:0,
                 from /home/mmvc/anaconda3/envs/SY_DANet/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:1:
/home/mmvc/anaconda3/envs/SY_DANet/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp: In lambda function:
/home/mmvc/anaconda3/envs/SY_DANet/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:425:27: error: expected primary-expression before ‘>’ token
       output.data<scalar_t>());
                           ^
/home/mmvc/anaconda3/envs/SY_DANet/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:425:29: error: expected primary-expression before ‘)’ token
       output.data<scalar_t>());
                             ^
/home/mmvc/anaconda3/envs/SY_DANet/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp: In lambda function:
/home/mmvc/anaconda3/envs/SY_DANet/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:425:27: error: expected primary-expression before ‘>’ token
       output.data<scalar_t>());
                           ^
/home/mmvc/anaconda3/envs/SY_DANet/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:425:29: error: expected primary-expression before ‘)’ token
       output.data<scalar_t>());
                             ^
/home/mmvc/anaconda3/envs/SY_DANet/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp: In function ‘at::Tensor ROIAlignBackwardCPU(const at::Tensor&, const at::Tensor&, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, double, int64_t)’:
/home/mmvc/anaconda3/envs/SY_DANet/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:454:37: error: ‘class at::DeprecatedTypeProperties’ has no member named ‘tensor’
   auto grad_in = bottom_rois.type().tensor({b_size, channels, height, width}).zero_(); 
                                     ^
In file included from /home/mmvc/anaconda3/envs/Rx/lib/python3.6/site-packages/torch/include/ATen/ATen.h:9:0,
                 from /home/mmvc/anaconda3/envs/SY_DANet/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:1:
/home/mmvc/anaconda3/envs/SY_DANet/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp: In lambda function:
/home/mmvc/anaconda3/envs/SY_DANet/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:470:28: error: expected primary-expression before ‘>’ token
       grad_in.data<scalar_t>(),
                            ^
/home/mmvc/anaconda3/envs/SY_DANet/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:470:30: error: expected primary-expression before ‘)’ token
       grad_in.data<scalar_t>(),
                              ^
/home/mmvc/anaconda3/envs/SY_DANet/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp: In lambda function:
/home/mmvc/anaconda3/envs/SY_DANet/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:470:28: error: expected primary-expression before ‘>’ token
       grad_in.data<scalar_t>(),
                            ^
/home/mmvc/anaconda3/envs/SY_DANet/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:470:30: error: expected primary-expression before ‘)’ token
       grad_in.data<scalar_t>(),
                              ^
ninja: build stopped: subcommand failed.
```
How to fix this?
What version of pytorch, cuda or python should I use?

**Comment by XU-GITHUB-curry** [comment]
I had the same problem as you

**Comment by Stephanessy** [comment]
@XU-GITHUB-curry Did you fix it?

**Comment by XU-GITHUB-curry** [comment]
> @XU-GITHUB-curry Did you fix it?

not yet. I can't figure it out ,so I put it on the Issues

**Comment by Stephanessy** [comment]
@XU-GITHUB-curry https://blog.csdn.net/m0_37759119/article/details/90730276
This might be helpful. I have another problem which is, for cpp_extension.py, it will try to reach other conda env (Rx), whereas my conda env is SY_DANet. Do you know why this happened?

**Comment by XU-GITHUB-curry** [comment]
> @XU-GITHUB-curry https://blog.csdn.net/m0_37759119/article/details/90730276
> This might be helpful. I have another problem which is, for cpp_extension.py, it will try to reach other conda env (Rx), whereas my conda env is SY_DANet. Do you know why this happened?

Sorry,I don't know .I am a rookie of this filed. May I ask you some codes which have pretrained nets about semantic segmentation. I want to run a easy-understanding and complete one.

**Comment by Stephanessy** [comment]
@XU-GITHUB-curry I am also a rookie🤣

**Comment by theevann** [comment]
I got it working by replacing the folder `encoding/lib/` of this repo with the folder `encoding/lib/` of the [official pytorch-encoding repo](https://github.com/zhanghang1989/PyTorch-Encoding).
(I hope this saves you the half day I took to figure that out)

**Comment by XU-GITHUB-curry** [comment]
> I got it working by replacing the folder `encoding/lib/` of this repo by the folder `encoding/lib/` of the [official pytorch-encoding repo](https://github.com/zhanghang1989/PyTorch-Encoding), and then re-installing with setup.py.
> (I hope this saves you the half day I took to figure that out)
> 
> Note: To transform the Cityscapes dataset, you need to clone [cityscapesscript](https://github.com/mcordts/cityscapesScripts) and install with setup.py (`python3 setup.py install --user`), then export the path to cityscapes to an env variable `export CITYSCAPES_DATASET=/foo/bar`, then to run `csCreateTrainIdLabelImgs`. Then I had to rename the created png with: `for file in $(ls */*/* | grep labelTrain); rename 's/labelT/t/' $file;` from the `leftImg8bit` folder.

sorry，I don't understand " then export the path to cityscapes to an env variable `export CITYSCAPES_DATASET=/foo/bar`,   " .can you explain it more clearly

**Comment by theevann** [comment]
Run the command `export CITYSCAPES_DATASET=/path/to/CityScapes` where you replace `/path/to/CityScapes` by the real path to your CityScapes dataset

**Comment by XU-GITHUB-curry** [comment]
> Run the command `export CITYSCAPES_DATASET=/path/to/CityScapes` where you replace `/path/to/CityScapes` by the real path to your CityScapes dataset

thank u ! I will try it

**Comment by domYuki** [comment]
> I got it working by replacing the folder encoding/lib/ of this repo by the folder encoding/lib/ of the official pytorch-encoding repo, and then re-installing with setup.py.
> (I hope this saves you the half day I took to figure that out)

I tried it.
I had another problem.

```
  File "train.py", line 201, in <module>
    trainer.training(epoch)
  File "train.py", line 125, in training
    outputs = self.model(image)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 143, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 153, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/---/danet_20200702/DANet/encoding/models/danet.py", line 45, in forward
    _, _, c3, c4 = self.base_forward(x)
  File "/home/---/danet_20200702/DANet/encoding/models/base.py", line 58, in base_forward
    x = self.pretrained.bn1(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/---/danet_20200702/DANet/encoding/nn/syncbn.py", line 51, in forward
    xsum, xsqsum = sum_square(input)
  File "/home/---/danet_20200702/DANet/encoding/functions/syncbn.py", line 19, in sum_square
    return _sum_square.apply(input)
  File "/home/---/danet_20200702/DANet/encoding/functions/syncbn.py", line 27, in forward
    xsum, xsqusum = lib.gpu.sumsquare_forward(input)
AttributeError: module 'enclib_gpu' has no attribute 'sumsquare_forward'
```

How to fix this?
I guess that version of Pytorch encoding and DANet is different.
(official pytorch-encoding( I used) :1.0.1, pytorch encoding of DANet:0.4.3)

env
python 3.6.8
torch 1.0.0
cuda 10.1

**Comment by domYuki** [comment]
I solved. (#^.^#)
Thanks

**Comment by theevann** [comment]
> I solved. (#^.^#)
> Thanks

Could you share ? Thanks

**Comment by domYuki** [comment]
OK！！！

PytorchEncoding version1.0.1->DANet

ENV
ubuntu 18.04.2 LTS
CUDA 10.0
Python 3.6.8
torch 1.0.0
torchvision 0.2.0
ninja 1.8.2
hacky 0.0.2

**①Install torch, torchvision, ninja, hacky**
・torch
pip install http://download.pytorch.org/whl/cu100/torch-1.0.0-cp36-cp36m-linux_x86_64.wh
・torchvision
pip install torchvision==0.2.0
・ninja
pip install ninja==1.8.2
・hacky
pip install hacky


**②install PytorchEncoding version1.0.1 & unzip**
・ download pytorch encoding v1.0.1
https://github.com/zhanghang1989/PyTorch-Encoding/releases/tag/v1.0.0

**③install PytorchEncoding**

cd PyTorch-Encoding
python setup.py install

**④replace**
PyTorch-Encoding v1.0.1              → DANet
-----------------------------------------------
encoding/lib                                 → encoding/lib
encoding/functions/syncbn.py    → encoding/functions/syncbn.py
encoding/nn/syncbn.py               → encoding/nn/syncbn.py
encoding/utils/misc.py                → encoding/utils/misc.py(create new file)

**Comment by wlj567** [comment]
@domYuki 您好，请问你这个代码跑出来了吗，方便加个联系方式吗

**Comment by wlj567** [comment]
> OK！！！
> 
> PytorchEncoding version1.0.1->DANet
> 
> ENV
> ubuntu 18.04.2 LTS
> CUDA 10.0
> Python 3.6.8
> torch 1.0.0
> torchvision 0.2.0
> ninja 1.8.2
> hacky 0.0.2
> 
> **①Install torch, torchvision, ninja, hacky**
> ・torch
> pip install http://download.pytorch.org/whl/cu100/torch-1.0.0-cp36-cp36m-linux_x86_64.wh
> ・torchvision
> pip install torchvision==0.2.0
> ・ninja
> pip install ninja==1.8.2
> ・hacky
> pip install hacky
> 
> **②install PytorchEncoding version1.0.1 & unzip**
> ・ download pytorch encoding v1.0.1
> https://github.com/zhanghang1989/PyTorch-Encoding/releases/tag/v1.0.0
> 
> **③install PytorchEncoding**
> 
> cd PyTorch-Encoding
> python setup.py install
> 
> **④replace**
> [PyTorch-Encoding v1.0.1] → [DANet]
> encoding/lib → encoding/lib
> encoding/functions/syncbn.py → encoding/functions/syncbn.py
> encoding/nn/syncbn.py → encoding/nn/syncbn.py
> encoding/utils/misc.py → encoding/utils/misc.py(create new file)
> encoding/version.py → encoding/version.py(create new file)
> 
> **・processing form 33 class to 19 class for Cityscapes**
> This will be helpful to fix dataloader
> [hszhao/semseg#29 (comment)](https://github.com/hszhao/semseg/issues/29#issuecomment-567225502)

您好，请问这个代码跑出来了吗，方便加个联系方式吗
