### ISSUE TITLE
No module named 'encoding'？how to solve it?

### ISSUE THREAD

**Issue by xkhnhms** [junfu1115/DANet#130]
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    import encoding.utils as utils
ModuleNotFoundError: No module named 'encoding'

**Comment by xkhnhms** [comment]
c++: 错误：unrecognized command line option ‘-std=c++14’
ninja: build stopped: subcommand failed.

**Comment by xkhnhms** [comment]
Traceback (most recent call last):
  File "encoding/datasets/ade20k.py", line 18, in <module>
    from .base import BaseDataset
ImportError: attempted relative import with no known parent package

**Comment by xinghaoxinghao** [comment]
> Traceback (most recent call last):
> File "encoding/datasets/ade20k.py", line 18, in 
> from .base import BaseDataset
> ImportError: attempted relative import with no known parent package

Have you solved this problem? I had the same problem

**Comment by xkhnhms** [comment]
> > Traceback (most recent call last):
> > File "encoding/datasets/ade20k.py", line 18, in
> > from .base import BaseDataset
> > ImportError: attempted relative import with no known parent package
> 
> Have you solved this problem? I had the same problem

I still can't solve it. This problem still exists.

**Comment by xkhnhms** [comment]
I still can't solve it. This problem still exists.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "junfu1115/DANet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月10日(星期一) 晚上9:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [junfu1115/DANet] No module named 'encoding'？how to solve it? (#130)





  
Traceback (most recent call last):
 File "encoding/datasets/ade20k.py", line 18, in
 from .base import BaseDataset
 ImportError: attempted relative import with no known parent package
  
Have you solved this problem? I had the same problem

**Comment by wlj567** [comment]
指定base文件路径

**Comment by wlj567** [comment]
@xkhnhms @xinghaoxinghao Hello, have you passed the complete code? Is it convenient to add a contact information? Thank you!
