### ISSUE TITLE
When i try to train or test danet i get this error 

### ISSUE THREAD

**Issue by ChaikhiBelaid** [junfu1115/DANet#136]
Traceback (most recent call last):
  File "test.py", line 216, in <module>
    test(args)
  File "test.py", line 131, in test
    model = get_segmentation_model(args.model, dataset=args.dataset,
  File "/home/belaid.chaikhi/.local/lib/python3.8/site-packages/encoding/models/sseg/__init__.py", line 20, in get_segmentation_model
    return models[name.lower()](**kwargs)
KeyError: 'danet'

**Comment by ChaikhiBelaid** [comment]
`Traceback (most recent call last):
  File "test.py", line 216, in <module>
    test(args)
  File "test.py", line 131, in test
    model = get_segmentation_model(args.model, dataset=args.dataset,
  File "/home/belaid.chaikhi/.local/lib/python3.8/site-packages/encoding/models/sseg/__init__.py", line 20, in get_segmentation_model
    return models[name.lower()](**kwargs)
KeyError: 'danet'
`
