### ISSUE TITLE
training error:outputs = self.model(image)

### ISSUE THREAD

**Issue by chichilicious** [junfu1115/DANet#31]
Hi,

So while trying to train the network I encountered this error. I can't figure out what the mistake is. I'm using the proper pytorch commit. 
From my terminal:
`CUDA_VISIBLE_DEVICES=0 python train.py --dataset cityscapes --model  danet --backbone resnet101 --checkname danet101  --base-size 1024 --crop-size 768 --epochs 240 --batch-size 8 --lr 0.003 --workers 2 --multi-grid --multi-dilation 4 8 16`

Error:
```=>Epoches 0, learning rate = 0.0030,                 previous best = 0.0000
Traceback (most recent call last):
  File "train.py", line 201, in <module>
    trainer.training(epoch)
  File "train.py", line 125, in training
    outputs = self.model(image)
  File "/datadrive/virtualenvs/torchDA/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/datadrive/virtualenvs/torchDA/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/datadrive/virtualenvs/torchDA/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/datadrive/virtualenvs/torchDA/lib/python3.6/site-packages/encoding/models/danet.py", line 45, in forward
    _, _, c3, c4 = self.base_forward(x)
  File "/datadrive/virtualenvs/torchDA/lib/python3.6/site-packages/encoding/models/base.py", line 58, in base_forward
    x = self.pretrained.bn1(x)
  File "/datadrive/virtualenvs/torchDA/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/datadrive/virtualenvs/torchDA/lib/python3.6/site-packages/encoding/nn/syncbn.py", line 57, in forward
    mean, inv_std = self._slave_pipe.run_slave(_ChildMessage(xsum, xsqsum, N))
AttributeError: 'NoneType' object has no attribute 'run_slave' ```

I have not made any modifications to the code.

**Comment by chichilicious** [comment]
Can this be run on single GPU? Or does it require multiple GPU?

**Comment by huanghoujing** [comment]
The sync_bn requires multi gpus. You can modify some code to use standard BN and get rid of data parallel logic, to train with one gpu.

**Comment by chichilicious** [comment]
@huanghoujing 
Can this be run for a k80 with 11gb?
I'm getting cuda,out of memory error.
Is there any way to decrease the batch size or some other hacks?

**Comment by huanghoujing** [comment]
Of course, you can decrease batch size, image size (some datasets do not require large image input), or even model size. Reducing sizes may affect performance, but if you do not require the best performance, just try it. E.g., reduce to 
- `--base-size 512`
- `--crop-size 384`
- `--batch-size 8`
- `--backbone resnet50`

**Comment by chichilicious** [comment]
Hi @huanghoujing,

I have made the following changes to my `train.py`

- https://github.com/junfu1115/DANet/blob/201d308581d9d5a780a99f425eb5aee53bf3680b/danet/train.py#L61 i have changed it to `norm_layer=torch.nn.BatchNorm2d`
- https://github.com/junfu1115/DANet/blob/201d308581d9d5a780a99f425eb5aee53bf3680b/danet/train.py#L83 I have changed it to `self.model = self.model.cuda()`
- https://github.com/junfu1115/DANet/blob/201d308581d9d5a780a99f425eb5aee53bf3680b/danet/train.py#L84 I have changed it to `self.criterion = self.criterion.cuda()`

From my terminal:
```CUDA_VISIBLE_DEVICES=0 python train.py --dataset cityscapes --model  danet --backbone resnet101 --checkname danet101  --base-size 1024 --crop-size 384 --epochs 240 --batch-size 8 --lr 0.003 --workers 2 --multi-grid --multi-dilation 4 8 16```

I'm getting this error, i think there is some GPU mismatch. are there any other lines i need to change?
``Traceback (most recent call last):
  File "train.py", line 201, in <module>
    trainer.training(epoch)
  File "train.py", line 125, in training
    outputs = self.model(image)
  File "/datadrive/virtualenvs/torchDA/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/datadrive/virtualenvs/torchDA/lib/python3.6/site-packages/encoding/models/danet.py", line 45, in forward
    _, _, c3, c4 = self.base_forward(x)
  File "/datadrive/virtualenvs/torchDA/lib/python3.6/site-packages/encoding/models/base.py", line 57, in base_forward
    x = self.pretrained.conv1(x)
  File "/datadrive/virtualenvs/torchDA/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/datadrive/virtualenvs/torchDA/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #2 'weight' ``

**Comment by yiqigo0215** [comment]
I have changed  norm_layer=torch.nn.BatchNorm2d,self.model = self.model.cuda(),  self.criterion = self.criterion.cuda(). While trying to train the network I encountered this error, site-packages/encoding/nn/customize.py", line 103, in forward
pred1, pred2 ,pred3= tuple(preds)
ValueError: not enough values to unpack (expected 3, got 1)

**Comment by zhenxingsh** [comment]
> I have changed norm_layer=torch.nn.BatchNorm2d,self.model = self.model.cuda(), self.criterion = self.criterion.cuda(). While trying to train the network I encountered this error, site-packages/encoding/nn/customize.py", line 103, in forward
> pred1, pred2 ,pred3= tuple(preds)
> ValueError: not enough values to unpack (expected 3, got 1)

is you have solved this error? and how solverd it ? i have also account this errors and have no idea about how to solve it.

**Comment by huanghoujing** [comment]
@chichilicious You have to put your data to GPU as well. Here is [an answer](https://discuss.pytorch.org/t/runtimeerror-expected-object-of-type-torch-floattensor-but-found-type-torch-cuda-floattensor-for-argument-2-weight/27483).

**Comment by yougoforward** [comment]
Hello, everyone! I have met this problem and solved it as follows:
in DANet/encoding/nn/syncbn.py line 36
        self._parallel_id = None
You need to set self._parallel_id=0 if you just have one GPU.
You can see line 61 __data_parallel_replicate__ function:
    def __data_parallel_replicate__(self, ctx, copy_id):
        self._parallel_id = copy_id

        # parallel_id == 0 means master device.
        if self._parallel_id == 0:
            ctx.sync_master = self._sync_master
        else:
            self._slave_pipe = ctx.sync_master.register_slave(copy_id)

**Comment by zhenmafan7** [comment]
> Hello, everyone! I have met this problem and solved it as follows:
> in DANet/encoding/nn/syncbn.py line 36
> self._parallel_id = None
> You need to set self._parallel_id=0 if you just have one GPU.
> You can see line 61 **data_parallel_replicate** function:
> def **data_parallel_replicate**(self, ctx, copy_id):
> self._parallel_id = copy_id
> 
> ```
>     # parallel_id == 0 means master device.
>     if self._parallel_id == 0:
>         ctx.sync_master = self._sync_master
>     else:
>         self._slave_pipe = ctx.sync_master.register_slave(copy_id)
> ```

Hi,I edit syncbn.py as you say, and I changed train.py line61,
Norm_layer=BatchNorm2d instead of  norm_layer=torch.nn.BatchNorm2d,
When I trying to run train.py, this error occured:
 File "train.py", line 205, in <module>
    trainer.training(epoch)
  File "train.py", line 130, in training
    loss = self.criterion(outputs, target)
  File "/home/wq/.conda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wq/.conda/envs/py36/lib/python3.6/site-packages/encoding/parallel.py", line 132, in forward
    return self.module(inputs, *targets[0], **kwargs[0])
  File "/home/wq/.conda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wq/.conda/envs/py36/lib/python3.6/site-packages/encoding/nn/customize.py", line 100, in forward
    pred1, pred2 ,pred3= tuple(preds)
ValueError: not enough values to unpack (expected 3, got 1)

Do you know how I can solve this problem?

**Comment by yougoforward** [comment]
for single gpu：
It should be
`pred1, pred2 ,pred3= tuple(preds[0])`

**Comment by zhenmafan7** [comment]
> Of course, you can decrease batch size, image size (some datasets do not require large image input), or even model size. Reducing sizes may affect performance, but if you do not require the best performance, just try it. E.g., reduce to
> 
> * `--base-size 512`
> * `--crop-size 384`
> * `--batch-size 8`
> * `--backbone resnet50`

hello,I decrease base size to 512, crop size 384
while I trying to run train.py,I encounter this problem:
raceback (most recent call last):
  File "train.py", line 206, in <module>
    trainer.validation(epoch)
  File "train.py", line 172, in validation
    correct, labeled, inter, union = eval_batch(self.model, image, target)
  File "train.py", line 158, in eval_batch
    inter, union = utils.batch_intersection_union(pred.data, target, self.nclass)
  File "/home/wq/.conda/envs/py36/lib/python3.6/site-packages/encoding/utils/metrics.py", line 44, in batch_intersection_union
    predict = predict * (target > 0).astype(predict.dtype)
ValueError: operands could not be broadcast together with shapes (19,384) (4,384,384) 
What could I do to solve this problem?

**Comment by yougoforward** [comment]
For eval_batch in train.py , comment the multi-gpu data collection line as follows:

        def eval_batch(model, image, target):
            outputs = model(image)
            # outputs = gather(outputs, 0, dim=0)
            pred = outputs[0]
            target = target.cuda()
            correct, labeled = utils.batch_pix_accuracy(pred.data, target)
            inter, union = utils.batch_intersection_union(pred.data, target, self.nclass)
            return correct, labeled, inter, union

**Comment by Mr-markdown** [comment]
Hi,
So while trying to train the network I encountered this error. I can't figure out what the mistake is.
I use a single GPU now!

THCudaCheck FAIL file=C:/a/w/1/s/windows/pytorch/aten/src/ATen/native/cuda/SoftMax.cu line=545 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "F:/Paper/1.now-read/DANet-master/danet/train.py", line 209, in <module>
    trainer.training(epoch)
  File "F:/Paper/1.now-read/DANet-master/danet/train.py", line 134, in training
    loss = self.criterion(outputs, target)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "F:\Paper\1.now-read\DANet-master\encoding\nn\customize.py", line 104, in forward
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\loss.py", line 904, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\functional.py", line 1970, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\functional.py", line 1295, in log_softmax
    ret = input.log_softmax(dim)
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at C:/a/w/1/s/windows/pytorch/aten/src/ATen/native/cuda/SoftMax.cu:545

**Comment by shoutOutYangJie** [comment]
> for single gpu：
> It should be
> `pred1, pred2 ,pred3= tuple(preds[0])`

hello. if you train DAnet with pretrained ResNet, please tell me where i can get pretrained  resnet model

**Comment by xdsonglinliu** [comment]
> Hi,
> So while trying to train the network I encountered this error. I can't figure out what the mistake is.
> I use a single GPU now!
> 
> THCudaCheck FAIL file=C:/a/w/1/s/windows/pytorch/aten/src/ATen/native/cuda/SoftMax.cu line=545 error=77 : an illegal memory access was encountered
> Traceback (most recent call last):
> File "F:/Paper/1.now-read/DANet-master/danet/train.py", line 209, in 
> trainer.training(epoch)
> File "F:/Paper/1.now-read/DANet-master/danet/train.py", line 134, in training
> loss = self.criterion(outputs, target)
> File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 489, in **call**
> result = self.forward(*input, **kwargs)
> File "F:\Paper\1.now-read\DANet-master\encoding\nn\customize.py", line 104, in forward
> File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\loss.py", line 904, in forward
> ignore_index=self.ignore_index, reduction=self.reduction)
> File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\functional.py", line 1970, in cross_entropy
> return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
> File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\functional.py", line 1295, in log_softmax
> ret = input.log_softmax(dim)
> RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at C:/a/w/1/s/windows/pytorch/aten/src/ATen/native/cuda/SoftMax.cu:545

I have met this problem. Have you solved this error?
@Mr-markdown

**Comment by DawnWalker** [comment]
> Hi @huanghoujing,
> 
> I have made the following changes to my `train.py`
> 
> * https://github.com/junfu1115/DANet/blob/201d308581d9d5a780a99f425eb5aee53bf3680b/danet/train.py#L61
>    i have changed it to `norm_layer=torch.nn.BatchNorm2d`
> * https://github.com/junfu1115/DANet/blob/201d308581d9d5a780a99f425eb5aee53bf3680b/danet/train.py#L83
>    I have changed it to `self.model = self.model.cuda()`
> * https://github.com/junfu1115/DANet/blob/201d308581d9d5a780a99f425eb5aee53bf3680b/danet/train.py#L84
>    I have changed it to `self.criterion = self.criterion.cuda()`
> 
> From my terminal:
> `CUDA_VISIBLE_DEVICES=0 python train.py --dataset cityscapes --model danet --backbone resnet101 --checkname danet101 --base-size 1024 --crop-size 384 --epochs 240 --batch-size 8 --lr 0.003 --workers 2 --multi-grid --multi-dilation 4 8 16`
> 
> I'm getting this error, i think there is some GPU mismatch. are there any other lines i need to change?
> 
> ```
> Traceback (most recent call last):
>   File "train.py", line 201, in <module>
>     trainer.training(epoch)
>   File "train.py", line 125, in training
>     outputs = self.model(image)
>   File "/datadrive/virtualenvs/torchDA/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/datadrive/virtualenvs/torchDA/lib/python3.6/site-packages/encoding/models/danet.py", line 45, in forward
>     _, _, c3, c4 = self.base_forward(x)
>   File "/datadrive/virtualenvs/torchDA/lib/python3.6/site-packages/encoding/models/base.py", line 57, in base_forward
>     x = self.pretrained.conv1(x)
>   File "/datadrive/virtualenvs/torchDA/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/datadrive/virtualenvs/torchDA/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
>     self.padding, self.dilation, self.groups)
> RuntimeError: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #2 'weight' 
> ```
> 
> This is my print statement for self.weight in `conv.py`, from the line
> 
> ```
> def forward(self, input):
>         return F.conv2d(input, self.weight, self.bias, self.stride,
>                         self.padding, self.dilation, self.groups)
> ```
> 
> `
> type(self.weight)
> 
> > > <class 'torch.nn.parameter.Parameter'>
> > > `

Hi, I got the same problem as yours, Do u solve it?

**Comment by Yvette1993** [comment]
Excuse me Sir. 
    After change the train.py following it, but I got that:
 RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same.
    Do you have any ideal?

> > Hi @huanghoujing,
> > I have made the following changes to my `train.py`
> > 
> > * https://github.com/junfu1115/DANet/blob/201d308581d9d5a780a99f425eb5aee53bf3680b/danet/train.py#L61
> >   
> >   i have changed it to `norm_layer=torch.nn.BatchNorm2d`
> > * https://github.com/junfu1115/DANet/blob/201d308581d9d5a780a99f425eb5aee53bf3680b/danet/train.py#L83
> >   
> >   I have changed it to `self.model = self.model.cuda()`
> > * https://github.com/junfu1115/DANet/blob/201d308581d9d5a780a99f425eb5aee53bf3680b/danet/train.py#L84
> >   
> >   I have changed it to `self.criterion = self.criterion.cuda()`
> > 
> > From my terminal:
> > `CUDA_VISIBLE_DEVICES=0 python train.py --dataset cityscapes --model danet --backbone resnet101 --checkname danet101 --base-size 1024 --crop-size 384 --epochs 240 --batch-size 8 --lr 0.003 --workers 2 --multi-grid --multi-dilation 4 8 16`
> > I'm getting this error, i think there is some GPU mismatch. are there any other lines i need to change?
> > ```
> > Traceback (most recent call last):
> >   File "train.py", line 201, in <module>
> >     trainer.training(epoch)
> >   File "train.py", line 125, in training
> >     outputs = self.model(image)
> >   File "/datadrive/virtualenvs/torchDA/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
> >     result = self.forward(*input, **kwargs)
> >   File "/datadrive/virtualenvs/torchDA/lib/python3.6/site-packages/encoding/models/danet.py", line 45, in forward
> >     _, _, c3, c4 = self.base_forward(x)
> >   File "/datadrive/virtualenvs/torchDA/lib/python3.6/site-packages/encoding/models/base.py", line 57, in base_forward
> >     x = self.pretrained.conv1(x)
> >   File "/datadrive/virtualenvs/torchDA/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
> >     result = self.forward(*input, **kwargs)
> >   File "/datadrive/virtualenvs/torchDA/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
> >     self.padding, self.dilation, self.groups)
> > RuntimeError: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #2 'weight' 
> > ```
> > 
> > 
> > This is my print statement for self.weight in `conv.py`, from the line
> > ```
> > def forward(self, input):
> >         return F.conv2d(input, self.weight, self.bias, self.stride,
> >                         self.padding, self.dilation, self.groups)
> > ```
> > 
> > 
> > `
> > type(self.weight)
> > > > <class 'torch.nn.parameter.Parameter'>
> > > > `
> 
> Hi @chichilicious, I got the same problem as yours, Did u solve it?

**Comment by Yvette1993** [comment]
> > Of course, you can decrease batch size, image size (some datasets do not require large image input), or even model size. Reducing sizes may affect performance, but if you do not require the best performance, just try it. E.g., reduce to
> > 
> > * `--base-size 512`
> > * `--crop-size 384`
> > * `--batch-size 8`
> > * `--backbone resnet50`
> 
> hello,I decrease base size to 512, crop size 384
> while I trying to run train.py,I encounter this problem:
> raceback (most recent call last):
> File "train.py", line 206, in
> trainer.validation(epoch)
> File "train.py", line 172, in validation
> correct, labeled, inter, union = eval_batch(self.model, image, target)
> File "train.py", line 158, in eval_batch
> inter, union = utils.batch_intersection_union(pred.data, target, self.nclass)
> File "/home/wq/.conda/envs/py36/lib/python3.6/site-packages/encoding/utils/metrics.py", line 44, in batch_intersection_union
> predict = predict * (target > 0).astype(predict.dtype)
> ValueError: operands could not be broadcast together with shapes (19,384) (4,384,384)
> What could I do to solve this problem?

Hello. I meet the same problem:ValueError: operands could not be broadcast together with shapes (19,384) (4,384,384).  How did you solve it?
