### ISSUE TITLE
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by xdsonglinliu** [junfu1115/DANet#70]
the environment configure:
CUDA10.0
VS2017
pytorch: 1.0.0
python:3.7
Win10
Anaconda3
torch_encoding-0.4.5-py3.7

when i run python,
`$ CUDA_VISIBLE_DEVICES=0,1 python train.py --dataset cityscapes --model  danet --backbone resnet101 --checkname danet101  --base-size 1024 --crop-size 768 --epochs 240 --batch-size 6 --lr 0.003 --workers 1 --multi-grid --multi-dilation 4 8 16`

 it could appeare below errors.
`C:\Users\MSIK\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py:184: UserWarning: Error checking compiler version for c++: [WinError 2] 系统找不到指定的文件。
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
信息: 用提供的模式无法找到文件。
Traceback (most recent call last):
  File "train.py", line 17, in <module>
    import encoding.utils as utils
  File "C:\Users\MSIK\Anaconda3\lib\site-packages\encoding\__init__.py", line 13, in <module>
    from . import nn, functions, parallel, utils, models, datasets, transforms
  File "C:\Users\MSIK\Anaconda3\lib\site-packages\encoding\nn\__init__.py", line 12, in <module>
    from .encoding import *
  File "C:\Users\MSIK\Anaconda3\lib\site-packages\encoding\nn\encoding.py", line 18, in <module>
    from ..functions import scaled_l2, aggregate, pairwise_cosine
  File "C:\Users\MSIK\Anaconda3\lib\site-packages\encoding\functions\__init__.py", line 2, in <module>
    from .encoding import *
  File "C:\Users\MSIK\Anaconda3\lib\site-packages\encoding\functions\encoding.py", line 14, in <module>
    from .. import lib
  File "C:\Users\MSIK\Anaconda3\lib\site-packages\encoding\lib\__init__.py", line 15, in <module>
    ], build_directory=cpu_path, verbose=False)
  File "C:\Users\MSIK\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 645, in load
    is_python_module)
  File "C:\Users\MSIK\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 814, in _jit_compile
    with_cuda=with_cuda)
  File "C:\Users\MSIK\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 859, in _write_ninja_file_and_build
    with_cuda=with_cuda)
  File "C:\Users\MSIK\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1064, in _write_ninja_file
    'cl']).decode().split('\r\n')
  File "C:\Users\MSIK\Anaconda3\lib\subprocess.py", line 389, in check_output
    **kwargs).stdout
  File "C:\Users\MSIK\Anaconda3\lib\subprocess.py", line 481, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.`

 How I can solve this problem? Anyone can help me? 
Thanks a lot.

**Comment by xdsonglinliu** [comment]
I have solved this problem.

**Comment by Guptajakala** [comment]
@xdsonglinliu Hi, may I ask how did you solve?

**Comment by xdsonglinliu** [comment]
@Guptajakala 
https://blog.csdn.net/m0_37759119/article/details/90730276

**Comment by Fariha1123** [comment]
@xdsonglinliu after solving ['where','cl'] error, did you faced the below error? 
**subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.**
