### ISSUE TITLE
meet a problem:subprocess.CalledProcessError

### ISSUE THREAD

**Issue by karawang1593** [junfu1115/DANet#73]
I run on the cmd interface of Windows system

Traceback (most recent call last):
  File "test.py", line 16, in \<module\>
    import encoding.utils as utils
  File "C:\Users\wanglu\Anaconda3\lib\site-packages\encoding\__init__.py", line 13, in \<module\>
    from . import nn, functions, dilated, parallel, utils, models, datasets
  File "C:\Users\wanglu\Anaconda3\lib\site-packages\encoding\nn\__init__.py", line 12, in \<module\>
    from .encoding import *
  File "C:\Users\wanglu\Anaconda3\lib\site-packages\encoding\nn\encoding.py", line 19, in \<module\>
    from ..functions import scaledL2, aggregate, pairwise_cosine
  File "C:\Users\wanglu\Anaconda3\lib\site-packages\encoding\functions\__init__.py", line 2, in \<module\>
    from .encoding import *
  File "C:\Users\wanglu\Anaconda3\lib\site-packages\encoding\functions\encoding.py", line 14, in \<module\>
    from .. import lib
  File "C:\Users\wanglu\Anaconda3\lib\site-packages\encoding\lib\__init__.py", line 12, in \<module\>
    ], build_directory=cpu_path, verbose=False)
  File "C:\Users\wanglu\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 644, in load
    is_python_module)
  File "C:\Users\wanglu\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 813, in _jit_compile
    with_cuda=with_cuda)
  File "C:\Users\wanglu\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 862, in _write_ninja_file_and_build
    with_cuda=with_cuda)
  File "C:\Users\wanglu\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1072, in _write_ninja_file
    'cl']).decode().split('\r\n')
  File "C:\Users\wanglu\Anaconda3\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "C:\Users\wanglu\Anaconda3\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

**Comment by nanian111** [comment]
你解决了吗  我遇到了相同的问题

**Comment by jiqixuexiaihaozhe** [comment]
请问有人解决了吗

**Comment by jiqixuexiaihaozhe** [comment]
> 我在Windows系统的cmd界面上运行
> 
> 回溯（最近一次调用）：
> <模块>中的文件“ test.py”，第16行，
> 将utils作为utils导入encoding.utils
> 文件“ C：\ Users \ wanglu \ Anaconda3 \ lib \ site-packages \ encoding_ _init_ _.py ”，位于<module>中的第13行
> 。导入nn，函数，扩展的，并行，utils，模型，数据集
> 文件“ C：\ Users \ wanglu \ Anaconda3 \ lib \ site-packages \ encoding \ nn_ _init_ _.py”，第12行，
> 来自.encoding 从..functions的
> <module>中
> ，导入* 文件“ C：\ Users \ wanglu \ Anaconda3 \ lib \ site-packages \ encoding \ nn \ encoding.py”，行19 导入scaledL2，聚合，pairwise_cosine
> 文件“ C：__
> 从进口.encoding *
> 文件“C：\用户\ wanglu \ Anaconda3 \ lib中\站点包\编码\功能\ encoding.py”，第14行，在<模块>
> 从进口.. LIB
> 文件“C：\用户\ wanglu \ Anaconda3 \ lib \ site-packages \ encoding \ lib_ _init_ _.py“，第12行，在<module>中
> ，build_directory = cpu_path，冗长= False）
> 文件“ C：\ Users \ wanglu \ Anaconda3 \ lib \ site -packages \ torch \ utils \ cpp_extension.py”，在加载
> is_python_module中，行644 ）
> 文件“ C：\ Users \ wanglu \ Anaconda3 \ lib \ site-packages \ torch \ utils \ cpp_extension.py”，行_jit_compile中的813行
> with_cuda = with_cuda）
> 文件“ C：\ Users \ wanglu \ Anaconda3 \ lib \ site-packages \ torch \ utils \ cpp_extension.py”，行862，在_write_ninja_file_and_build
> with_cuda = with_cuda中）
> 文件“ C：\ Users \ wanglu \ Anaconda3 \ lib \ site-packages \ torch \ utils \ cpp_extension.py”，第1072行，位于_write_ninja_file'c​​l
> ']）。decode（）。split（'\ r \ n'）
> 文件“ C：\ Users \ wanglu \ Anaconda3 \ lib \ subprocess.py”，行395，位于check_output
> ** kwargs）.stdout
> 文件“ C：\ Users \ wanglu \ Anaconda3 \ lib \ subprocess.py”，行487，在运行
> output = stdout，stderr = stderr）
> subprocess.CalledProcessError：命令'['where'，'cl']'返回非零退出状态1。

我也遇到了这个问题，是怎么回事呢

**Comment by Ysoleil** [comment]
请问有人解决了这个问题吗？
