### ISSUE TITLE
where is the version in encoding?

### ISSUE THREAD

**Issue by Andy-zhujunwen** [junfu1115/DANet#77]
where is the .version in encoding?
in __init__.py of encoding,there is a .version,but i can not find it.

**Comment by initbin** [comment]
Hi, I have same problem. The error:
ModuleNotFoundError: No module named 'encoding.version'.
have you solved it?

**Comment by shallbyby** [comment]
Hi, I have the same problem.
so, i commented this line. but , I got some other problems.

**Comment by Bodhi-robbery** [comment]
hi,Have you ever had this problem?Thanks!
Traceback (most recent call last):
  File "train.py", line 201, in <module>
    trainer = Trainer(args)
  File "train.py", line 41, in __init__
    self.logger = utils.create_logger(args.log_root, args.log_name)
AttributeError: module 'encoding.utils' has no attribute 'create_logger'

**Comment by XUYUNYUN666** [comment]
> where is the .version in encoding?
> in **init**.py of encoding,there is a .version,but i can not fi

> Hi, I have same problem. The error:
> ModuleNotFoundError: No module named 'encoding.version'.
> have you solved it?

Have you solved the problem ?  I also encounter the error?

**Comment by shallbyby** [comment]
sorry，I can not find it yet!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Eirun_Xu"<notifications@github.com&gt;; 
发送时间: 2019年12月19日(星期四) 下午4:37
收件人: "junfu1115/DANet"<DANet@noreply.github.com&gt;; 
抄送: "Rivers"<924029356@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [junfu1115/DANet] where is the version in encoding? (#77)



 
where is the .version in encoding?
 in init.py of encoding,there is a .version,but i can not fi
   
Hi, I have same problem. The error:
 ModuleNotFoundError: No module named 'encoding.version'.
 have you solved it?
  
Have you solved the problem ?  I also encounter the error?
